### ISSUE TITLE
Cannot use unicode chars in preview at Japanese Windows 8

### ISSUE THREAD

**Issue by yukoba** [antlr/intellij-plugin-v4#148]
I'm using Japanese Windows 8 and the default encoding of Japanese Windows 8 is `Windows-31J`.
In the preview window of IntelliJ IDEA 13, I think UTF-8 and Windows-31J is confused,
and I cannot use unicode chars.
As far as I tested, all the other places have no problem if I configure grammar file encoding UTF-8.

**Comment by parrt** [comment]
I don't see how there can be an encoding issue with the Preview input editor as it's asking for a String which is straight unicode:

```
final String inputText = editor.getDocument().getText();
ParsingResult results = controller.parseText(grammarFile, inputText);
```

Are you able to use Japanese chars inside the *grammar editor*?

**Comment by yukoba** [comment]
> Are you able to use Japanese chars inside the grammar editor?

Yes. I was able to use at IntelliJ IDEA 14.

By the way, I cannot use ANTLR plugin with IntelliJ IDEA 15. Because of this.

```
update failed for AnAction with ID=antlr.TestRule: EXPECTED_CARET_OFFSET
java.lang.NoSuchFieldError: EXPECTED_CARET_OFFSET
	at org.antlr.intellij.plugin.actions.TestRuleAction.getSelectedRuleName(TestRuleAction.java:103)
	at org.antlr.intellij.plugin.actions.TestRuleAction.update(TestRuleAction.java:40)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:114)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:188)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:139)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:95)
	at com.intellij.openapi.editor.impl.EditorImpl$MyEditorPopupHandler.a(EditorImpl.java:7215)
	at com.intellij.openapi.editor.impl.EditorImpl$MyEditorPopupHandler.mouseReleased(EditorImpl.java:7191)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.c(EditorImpl.java:5824)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:5725)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by parrt** [comment]
yes, already reported. thanks. closing.

**Comment by yukoba** [comment]
No. Please do not close.
I was not able to use UTF-8 grammar files.

**Comment by yukoba** [comment]
If you want to reproduce, I think you can reproduce it by adding ```-Dfile.encoding=MS932```.
This is the default of Japanese Windows.

**Comment by parrt** [comment]
Ok,So now we have three bugs in one issue. please create another that specifically states that the grammar editor and not the input editor cannot handle different encodings.

**Comment by yukoba** [comment]
Three bugs???
I'm also confused with how you understand the situation.
I want to report only one bug.

I tested again.

- Japanese Windows 10
- IntelliJ IDEA 14.1.4
- ANTLR v4 grammar plugin 1.7

Source code. Only includes Test.g4.
https://github.com/yukoba/AntlrPluginBugTest 

This is the screenshot.
![1](https://github-cloud.s3.amazonaws.com/assets%2F194666%2F10957294%2F415ff238-83a6-11e5-8b57-34b958c41b4e.png)

Cannot handle ⇔ properly.
This is the bug what I want to report. Only 1 bug.

Encoding
- Grammar file is UTF-8.
- Default encoding of Japanese Windows is MS932. 

bin\idea.exe.vmoptions does not include ```-Dfile.encoding```, but in Japanese Windows, the default is ```-Dfile.encoding=MS932```.

Should I create a new issue report?
