### ISSUE TITLE
Problem loading Structure View in Intellij 14.1

### ISSUE THREAD

**Issue by UlTriX** [antlr/intellij-plugin-v4#177]
In Intellij 14.1 it gives the following error

AbstractMethodError: com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureViewModel(Lcom/intellij/openapi/editor/Editor;)Lcom/intellij/ide/structureView/StructureViewModel;

**Comment by itzg** [comment]
I am also seeing this in IntelliJ 14.1 (version 1.6 of the plugin)

Here's the full stacktrace:
```
java.lang.AbstractMethodError
	at com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureView(TreeBasedStructureViewBuilder.java:50)
	at com.intellij.ide.impl.StructureViewWrapperImpl.rebuild(StructureViewWrapperImpl.java:315)
	at com.intellij.ide.impl.StructureViewWrapperImpl$6.run(StructureViewWrapperImpl.java:253)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2379)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:266)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by rojaster** [comment]
I fixed it and my project works great without crashes like this.

**Comment by parrt** [comment]
Downloading 14.1 community edition to try it out. sounds like we may have a compilation issue with a single source across versions :(

**Comment by zbdzzg** [comment]
Is it fixed now? I am under the same issue using IDEA version 14.1.3 and plugin version 1.6.

**Comment by rojaster** [comment]
Problem look fixed and changes was merged

**Comment by parrt** [comment]
Still hoping for antlr/plugin release soon.

**Comment by itzg** [comment]
:+1: confirmed version 1.7 of the plugin resolves this

**Comment by parrt** [comment]
Hmm...I'm still getting it now. 14.1.5 and jdk 6.

**Comment by parrt** [comment]
ooops. i had 1.6 plugin running. ;)
