### ISSUE TITLE
"No start rule is selected" and "line 1:0 No viable alternative at input '<EOF>'" and "NullPointerException"

### ISSUE THREAD

**Issue by samjamesobrien** [antlr/intellij-plugin-v4#179]
For context the plugin had previously been working briefly, and I am using Intellij 13.1.6 on Ubuntu 14.04

Now when I right click on a rule and select 'Test rule' I see "line 1:0 No viable alternative at input '\<EOF\>'" at the bottom of the text input panel.

Once I start to type I see "No start rule is selected" in the parse tree panel.

There is no tool output, there is a NullPointerException in the event log each time I right click and select test rule.

The solutions mentioned in the other similar issue registered for me do not work, such as removing and re-installing the plugin, invalidating the cache and restarting.

As the plugin briefly worked before I expect it has gotten into some sort of bad state, I would like to know where all the settings are stored for the plugin so that I may delete them and try again. I have looked in several of the usual places and not succeeded.

Thanks

**Comment by samjamesobrien** [comment]
Issue was also found on OSX 10.9, and on Intellij 14 on the Ubuntu machine and the OSX machine.

**Comment by parrt** [comment]
Can you send the null ptr exception and related from the logs?

**Comment by samjamesobrien** [comment]
@parrt Just at the moment I cannot replicate the null pointer exception, I will put a bit of time into this soon and forward on what I have.

**Comment by jevring** [comment]
I can replicate it every time.
I did some tests with an extra grammar file. I called it "Test.g", forced the antlr plugin to handle it, realized I should have named it "Test.g4", renamed the file, and after that, no matter what I do, I get this exception. I've even removed "Test.g4", and I'm back with my previous grammar, and I always get this exception.

It could be related, but I don't even get a white background window in which to type. The window remains gray.

Anyway, here's the exception:
```
java.lang.NullPointerException
	at org.antlr.intellij.plugin.preview.PreviewPanel.updateParseTreeFromDoc(PreviewPanel.java:246)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.setStartRuleNameEvent(ANTLRv4PluginController.java:251)
	at org.antlr.intellij.plugin.actions.TestRuleAction.actionPerformed(TestRuleAction.java:82)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jevring** [comment]
Hmm, interestingly, when I stop using a split screen (my grammar file was alone in the right pane, with several java files in the left) it starts working again.

**Comment by parrt** [comment]
yep, i saw same thing. split is a problem.

**Comment by samjamesobrien** [comment]
I almost exclusively use split windows too.

**Comment by parrt** [comment]
Dup of https://github.com/antlr/intellij-plugin-v4/issues/162
