### ISSUE TITLE
NullPointerException in InputPanel.clearGrammarHighlighters

### ISSUE THREAD

**Issue by Hini77** [antlr/intellij-plugin-v4#203]
When I do a CTRL+SHIFT+F9 + CTRL+SHIFT+G the IntelliJ event log window shows a NullPointerException

null
java.lang.NullPointerException
	at org.antlr.intellij.plugin.preview.InputPanel.clearGrammarHighlighters(InputPanel.java:461)
	at org.antlr.intellij.plugin.profiler.ProfilerPanel.mouseEnteredGrammarEditorEvent(ProfilerPanel.java:99)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.mouseEnteredGrammarEditorEvent(ANTLRv4PluginController.java:288)
	at org.antlr.intellij.plugin.ANTLRv4PluginController$GrammarEditorMouseAdapter.mouseClicked(ANTLRv4PluginController.java:521)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseClickedCommand(EditorImpl.java:5650)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:5580)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I don't know if it's related or not, but when I'm in the ANTLR preview window and I have a valid testing code for my grammar, if I modify the testing code and introduce a syntax error on purpose, the preview window shows the error (but not the way 1.6 ANTLR IntelliJ pluggin did in the past) but if I correct the testing code to a valid one again, the preview window continue showing the previous errors.
It's a little confusing if you are trying to debug a complex grammar making some little changes.

Thank you by the way for all of your hard work!

**Comment by parrt** [comment]
Wow. :)   what is CTRL+F9 + CTRL+G supposed to do?

**Comment by Hini77** [comment]
Ups! ''^_^
I'm sorry, It's my fault! I meant CTRL+SHIFT+F9 and CTRL+SHIFT+G. I edited my previous post.
If I can help you to trace for the error I'll be very glad to help you

**Comment by curtosis** [comment]
I'm getting this exact error & stack trace without doing anything other than clicking around while writing a grammar.

It may or may not be related, but I'm also seeing weirdness with the preview pane - it's not using the current build of the grammar at all (detecting tokens with names that don't exist anymore).

**Comment by ringodingo** [comment]
I'm hitting the same thing - just by creating and opening a new project. 
null
java.lang.NullPointerException
	at org.antlr.intellij.plugin.preview.InputPanel.clearGrammarHighlighters(InputPanel.java:461)
	at org.antlr.intellij.plugin.profiler.ProfilerPanel.mouseEnteredGrammarEditorEvent(ProfilerPanel.java:99)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.mouseEnteredGrammarEditorEvent(ANTLRv4PluginController.java:288)
	at org.antlr.intellij.plugin.ANTLRv4PluginController$GrammarEditorMouseAdapter.mouseClicked(ANTLRv4PluginController.java:521)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.b(EditorImpl.java:5650)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:5580)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)

**Comment by parrt** [comment]
thanks. I will be getting to it.

**Comment by parrt** [comment]
Hi. which intellij? can you pass me a log showing this? Help > show log files

**Comment by parrt** [comment]
I get this in 1.6 jdk but not 1.7.
