### ISSUE TITLE
AbstractMethodError in Intellij code

### ISSUE THREAD

**Issue by parrt** [antlr/intellij-plugin-v4#220]
14.1.4, 14.1.5 give this error. unknown cause. happens all the time.

```
2015-11-01 12:11:54,514 [  89061]   INFO -  ANTLR ANTLRv4PluginController - currentEditorFileChangedEvent none -> /Users/parrt/antlr/code/antlr4/tool/pom.xml antlr4-master 
2015-11-01 12:11:54,549 [  89096]   INFO -  ANTLR ANTLRv4PluginController - currentEditorFileChangedEvent /Users/parrt/antlr/code/antlr4/tool/pom.xml -> /Users/parrt/antlr/code/antlr4/tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg antlr4-master 
2015-11-01 12:11:54,717 [  89264]   INFO -  ANTLR ANTLRv4PluginController - currentEditorFileChangedEvent none -> /usr/local/lib/antlr-4.4-complete.jar!/org/antlr/v4/runtime/tree/AbstractParseTreeVisitor.class lavac 
2015-11-01 12:11:54,775 [  89322]   INFO -  ANTLR ANTLRv4PluginController - currentEditorFileChangedEvent /usr/local/lib/antlr-4.4-complete.jar!/org/antlr/v4/runtime/tree/AbstractParseTreeVisitor.class -> /Users/parrt/bitbucket/lavac/tests/samples/sort.olava lavac 
2015-11-01 12:11:54,896 [  89443]   INFO -  ANTLR ANTLRv4PluginController - currentEditorFileChangedEvent none -> /Users/parrt/antlr/code/intellij-plugin-v4/src/java/org/antlr/intellij/plugin/preview/AltLabelTextProvider.java intellij-plugin-v4 
2015-11-01 12:11:54,926 [  89473]   INFO -  ANTLR ANTLRv4PluginController - currentEditorFileChangedEvent /Users/parrt/antlr/code/intellij-plugin-v4/src/java/org/antlr/intellij/plugin/preview/AltLabelTextProvider.java -> /Users/parrt/antlr/code/intellij-plugin-v4/src/java/org/antlr/intellij/plugin/preview/PreviewPanel.java intellij-plugin-v4 
2015-11-01 12:11:59,413 [  93960]   INFO -  ANTLR ANTLRv4PluginController - currentEditorFileChangedEvent /Users/parrt/antlr/code/intellij-plugin-v4/src/java/org/antlr/intellij/plugin/preview/PreviewPanel.java -> /Users/parrt/antlr/code/intellij-plugin-v4/src/grammars/org/antlr/intellij/plugin/parser/ANTLRv4Parser.g4 intellij-plugin-v4 
2015-11-01 12:11:59,413 [  93960]   INFO -  ANTLR ANTLRv4PluginController - loadGrammars /Users/parrt/antlr/code/intellij-plugin-v4/src/grammars/org/antlr/intellij/plugin/parser/ANTLRv4Parser.g4 intellij-plugin-v4 
2015-11-01 12:11:59,698 [  94245]   INFO -  ANTLR ANTLRv4PluginController - loadGrammars parser ANTLRv4Parser 
2015-11-01 12:12:00,164 [  94711]   INFO -             ANTLR PreviewPanel - switchToGrammar /Users/parrt/antlr/code/intellij-plugin-v4/src/grammars/org/antlr/intellij/plugin/parser/ANTLRv4Parser.g4 intellij-plugin-v4 
2015-11-01 12:12:00,170 [  94717]   INFO -               ANTLR InputPanel - switchToGrammar /Users/parrt/antlr/code/intellij-plugin-v4/src/grammars/org/antlr/intellij/plugin/parser/ANTLRv4Parser.g4 intellij-plugin-v4 
2015-11-01 12:12:00,172 [  94719]   INFO -               ANTLR InputPanel - createEditor: create new editor for /Users/parrt/antlr/code/intellij-plugin-v4/src/grammars/org/antlr/intellij/plugin/parser/ANTLRv4Parser.g4 intellij-plugin-v4 
2015-11-01 12:12:01,258 [  95805]   INFO -  ANTLR ANTLRv4PluginController - currentEditorFileChangedEvent /Users/parrt/antlr/code/intellij-plugin-v4/src/grammars/org/antlr/intellij/plugin/parser/ANTLRv4Parser.g4 -> /Users/parrt/antlr/code/intellij-plugin-v4/src/grammars/org/antlr/intellij/plugin/parser/ANTLRv4Lexer.g4 intellij-plugin-v4 
2015-11-01 12:12:01,258 [  95805]   INFO -  ANTLR ANTLRv4PluginController - loadGrammars /Users/parrt/antlr/code/intellij-plugin-v4/src/grammars/org/antlr/intellij/plugin/parser/ANTLRv4Lexer.g4 intellij-plugin-v4 
2015-11-01 12:12:01,377 [  95924]   INFO -  ANTLR ANTLRv4PluginController - loadGrammars lexer ANTLRv4Lexer 
2015-11-01 12:12:01,378 [  95925]   INFO -  ANTLR ANTLRv4PluginController - loadGrammars /Users/parrt/antlr/code/intellij-plugin-v4/src/grammars/org/antlr/intellij/plugin/parser/ANTLRv4Parser.g4 intellij-plugin-v4 
2015-11-01 12:12:01,662 [  96209]   INFO -  ANTLR ANTLRv4PluginController - loadGrammars parser ANTLRv4Parser 
2015-11-01 12:12:01,920 [  96467]   INFO -             ANTLR PreviewPanel - switchToGrammar /Users/parrt/antlr/code/intellij-plugin-v4/src/grammars/org/antlr/intellij/plugin/parser/ANTLRv4Lexer.g4 intellij-plugin-v4 
2015-11-01 12:12:01,920 [  96467]   INFO -               ANTLR InputPanel - switchToGrammar /Users/parrt/antlr/code/intellij-plugin-v4/src/grammars/org/antlr/intellij/plugin/parser/ANTLRv4Lexer.g4 intellij-plugin-v4 
2015-11-01 12:12:01,920 [  96467]   INFO -               ANTLR InputPanel - createEditor: create new editor for /Users/parrt/antlr/code/intellij-plugin-v4/src/grammars/org/antlr/intellij/plugin/parser/ANTLRv4Lexer.g4 intellij-plugin-v4 
2015-11-01 12:12:03,524 [  98071]  ERROR - til.concurrency.QueueProcessor - com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureViewModel(Lcom/intellij/openapi/editor/Editor;)Lcom/intellij/ide/structureView/StructureViewModel; 
java.lang.AbstractMethodError: com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureViewModel(Lcom/intellij/openapi/editor/Editor;)Lcom/intellij/ide/structureView/StructureViewModel;
	at com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureView(TreeBasedStructureViewBuilder.java:50)
	at com.intellij.ide.impl.StructureViewWrapperImpl.rebuild(StructureViewWrapperImpl.java:315)
	at com.intellij.ide.impl.StructureViewWrapperImpl$6.run(StructureViewWrapperImpl.java:253)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2350)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:266)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2015-11-01 12:12:03,527 [  98074]  ERROR - til.concurrency.QueueProcessor - IntelliJ IDEA 14.1.5  Build #IU-141.2735.5 
2015-11-01 12:12:03,527 [  98074]  ERROR - til.concurrency.QueueProcessor - JDK: 1.6.0_65 
2015-11-01 12:12:03,527 [  98074]  ERROR - til.concurrency.QueueProcessor - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-11-01 12:12:03,527 [  98074]  ERROR - til.concurrency.QueueProcessor - Vendor: Apple Inc. 
2015-11-01 12:12:03,527 [  98074]  ERROR - til.concurrency.QueueProcessor - OS: Mac OS X 
2015-11-01 12:12:03,528 [  98075]  ERROR - til.concurrency.QueueProcessor - Last Action:  
2015-11-01 12:12:04,191 [  98738]   INFO -  ANTLR ANTLRv4PluginController - currentEditorFileChangedEvent /Users/parrt/antlr/code/intellij-plugin-v4/src/grammars/org/antlr/intellij/plugin/parser/ANTLRv4Lexer.g4 -> /Users/parrt/antlr/code/intellij-plugin-v4/src/grammars/org/antlr/intellij/plugin/parser/ANTLRv4Parser.g4 intellij-plugin-v4 
```

**Comment by parrt** [comment]
Dup of #177

**Comment by parrt** [comment]
1.7 plugin fixes this. doh!
