### ISSUE TITLE
null ptr when showing lookahead interpretations in Java grammar

### ISSUE THREAD

**Issue by parrt** [antlr/intellij-plugin-v4#255]
It was class declaration start rule and two fields like `class T { double[] x; int y;}` and then click on profiler decision with k=6 lookahead.

```
java.lang.NullPointerException
	at org.antlr.v4.runtime.tree.Trees.findNodeSuchThat(Trees.java:270)
	at org.antlr.intellij.plugin.parsing.ParsingUtils.findOverriddenDecisionRoot(ParsingUtils.java:565)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog.setTrees(ShowAmbigTreesDialog.java:228)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog.popupLookaheadTreesDialog(ShowAmbigTreesDialog.java:185)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog$4.run(ShowAmbigTreesDialog.java:145)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by WolfgangFahl** [comment]
same as #258?
