### ISSUE TITLE
showAllPhraseInterpretations fails with NullPointerException

### ISSUE THREAD

**Issue by WolfgangFahl** [antlr/intellij-plugin-v4#258]
With the grammar from ANTLR Issue 994 
https://github.com/antlr/antlr4/issues/994

and testing expr with input 
```a and b or b and not c```

clicking the read ambiguity line and right clicking "show all phrase interpretations"
```java.lang.NullPointerException
	at org.antlr.v4.runtime.tree.Trees.findNodeSuchThat(Trees.java:270)
	at org.antlr.intellij.plugin.parsing.ParsingUtils.findOverriddenDecisionRoot(ParsingUtils.java:565)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog.setTrees(ShowAmbigTreesDialog.java:228)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog.popupAmbigTreesDialog(ShowAmbigTreesDialog.java:127)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog$3.run(ShowAmbigTreesDialog.java:84)```

**Comment by WolfgangFahl** [comment]
the Context tree ctx is null because the following code provides null trees:

```
public static List<ParserRuleContext> getAllPossibleParseTrees(Grammar g, Parser originalParser, TokenStream tokens, int decision, BitSet alts, int startIndex, int stopIndex, int startRuleIndex) throws RecognitionException {
        ArrayList trees = new ArrayList();
        ParserInterpreter parser = deriveTempParserInterpreter(g, originalParser, tokens);

        for(int alt = alts.nextSetBit(0); alt >= 0; alt = alts.nextSetBit(alt + 1)) {
            parser.reset();
            parser.addDecisionOverride(decision, startIndex, alt);
            ParserRuleContext t = parser.parse(startRuleIndex);
            GrammarInterpreterRuleContext ambigSubTree = (GrammarInterpreterRuleContext)Trees.getRootOfSubtreeEnclosingRegion(t, startIndex, stopIndex);
            if(Trees.isAncestorOf(parser.getOverrideDecisionRoot(), ambigSubTree)) {
                ambigSubTree = (GrammarInterpreterRuleContext)parser.getOverrideDecisionRoot();
            }

            trees.add(ambigSubTree);
        }

        return trees;
```
there should IMHO be a check that ambigSubTree is not null before adding it ...
