### ISSUE TITLE
Plugin giving NPE's on (incomplete) grammar

### ISSUE THREAD

**Issue by igmar** [antlr/intellij-plugin-v4#271]
Hi,

I've got a few NPE's : 

`
2016-07-13 14:48:11,293 [  44852]   INFO -        ANTLRv4PluginController - currentEditorFileChangedEvent none -> /Users/igmar/work/projects.git/rythm2/src/main/java/org/rythmengine/RythmEngine.java rythm2
2016-07-13 14:48:11,587 [  45146]   INFO -        ANTLRv4PluginController - currentEditorFileChangedEvent /Users/igmar/work/projects.git/rythm2/src/main/java/org/rythmengine/RythmEngine.java -> /Users/igmar/work/projects.git/rythm2/src/main/antlr4/RythmGrammar.g4 rythm2
2016-07-13 14:48:11,803 [  45362]   INFO -        ANTLRv4PluginController - loadGrammars /Users/igmar/work/projects.git/rythm2/src/main/antlr4/RythmGrammar.g4 rythm2
2016-07-13 14:48:11,838 [  45397]  ERROR -        ANTLRv4PluginController - File /Users/igmar/work/projects.git/rythm2/src/main/antlr4/RythmLexer.g4 couldn't be parsed as a lexer grammar: [error(99): RythmLexer.g4::: grammar RythmLexer has no rules]
java.lang.NullPointerException
        at org.antlr.v4.semantics.SymbolChecks.checkForModeConflicts(SymbolChecks.java:278)
        at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:132)
        at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:399)
        at org.antlr.v4.Tool.process(Tool.java:386)
        at org.antlr.v4.Tool.loadGrammar(Tool.java:606)
        at org.antlr.intellij.plugin.parsing.ParsingUtils.loadLexerGrammarFor(ParsingUtils.java:510)
        at org.antlr.intellij.plugin.parsing.ParsingUtils.loadGrammars(ParsingUtils.java:447)
        at org.antlr.intellij.plugin.ANTLRv4PluginController.updateGrammarObjectsFromFile_(ANTLRv4PluginController.java:362)
        at org.antlr.intellij.plugin.ANTLRv4PluginController.updateGrammarObjectsFromFile(ANTLRv4PluginController.java:346)
        at org.antlr.intellij.plugin.ANTLRv4PluginController.currentEditorFileChangedEvent(ANTLRv4PluginController.java:283)
        at org.antlr.intellij.plugin.ANTLRv4PluginController$MyFileEditorManagerAdapter.selectionChanged(ANTLRv4PluginController.java:552)
        at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
        at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:377)
        at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:364)
        at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:350)
        at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:343)
        at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
        at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
        at com.sun.proxy.$Proxy87.selectionChanged(Unknown Source)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:1593)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$9$1.run(FileEditorManagerImpl.java:1069)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:631)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:615)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:585)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.b(FocusManagerImpl.java:481)
        at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2397)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:461)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:456)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:64)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$9.run(FileEditorManagerImpl.java:1066)
        at com.intellij.openapi.util.BusyObject$Impl$Simple.execute(BusyObject.java:123)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.notifyPublisher(FileEditorManagerImpl.java:1062)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.fireSelectionChanged(FileEditorManagerImpl.java:1593)
        at com.intellij.openapi.fileEditor.impl.EditorsSplitters.a(EditorsSplitters.java:624)
        at com.intellij.openapi.fileEditor.impl.EditorsSplitters.setCurrentWindow(EditorsSplitters.java:633)
        at com.intellij.openapi.fileEditor.impl.EditorWindow.setEditor(EditorWindow.java:687)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:904)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:863)
`

and

`2016-07-14 09:46:53,110 [68366669]  ERROR -       ANTLRv4ExternalAnnotator - antlr can't process RythmLexer.g4
java.lang.NullPointerException
        at org.antlr.v4.semantics.SymbolChecks.checkForModeConflicts(SymbolChecks.java:278)
        at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:132)
        at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:399)
        at org.antlr.v4.Tool.process(Tool.java:386)
        at org.antlr.intellij.plugin.ANTLRv4ExternalAnnotator.doAnnotate(ANTLRv4ExternalAnnotator.java:112)
        at org.antlr.intellij.plugin.ANTLRv4ExternalAnnotator.doAnnotate(ANTLRv4ExternalAnnotator.java:44)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:212)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
        at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:260)
        at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:274)
        at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:229)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
        at com.intellij.util.Alarm$Request$1.run(Alarm.java:377)
        at com.intellij.util.Alarm$Request.run(Alarm.java:388)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
        at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
        at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
        at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

**Comment by parrt** [comment]
hi. can you send me the fragment that causes these?
