### ISSUE TITLE
Ambiguities tree fails to load

### ISSUE THREAD

**Issue by nielsbasjes** [antlr/intellij-plugin-v4#272]
[Context: IntelliJ 2016.2  plugin version 1.8.1]
I'm trying to fix the ambiguities in my parser using the plugin and on a regular basis is fails to popup.

I think the error may be related to the usage pattern of: having an error; without closing the popup edit the file and then opening the dialog again to show the new error situation.

In the error log of IntelliJ I found this stacktrace as the underlying error:

```
Index: 2, Size: 2
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog.setTrees(ShowAmbigTreesDialog.java:308)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog.popupAmbigTreesDialog(ShowAmbigTreesDialog.java:135)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog$3.run(ShowAmbigTreesDialog.java:92)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1390)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by parrt** [comment]
Hi. I just fixed this. (I hope). I'll push out a release soon.

**Comment by nielsbasjes** [comment]
Thanks. I did some testing and it didn't crash any more.
