### ISSUE TITLE
Plugin crashing

### ISSUE THREAD

**Issue by NathanielOstrer** [antlr/intellij-plugin-v4#275]
I'm pretty sure this plugin has a memory leak somewhere, because whenever I run it now it keeps adding memory until intellij crashes

**Comment by parrt** [comment]
Hmm...it's possible I guess. Can you provide more info? Why do you think it's ANTLR plugin?

**Comment by parrt** [comment]
@higgs241 any more info?

**Comment by kiranmohantp** [comment]
Hello @parrt ,
I am facing the same issue in intelliJ community edition 2019.1.3 with latest version of plugin.
I can see memory usage of intelliJ shooting up to more than 4gb rapidly and my ide get crashed

**Comment by kiranmohantp** [comment]
Please note that this issue was not present at the initial stage(few times after the first installation of the plugin) later only it started to show up
Please find some screen shots . 
* This attachment was made using an application called step recorder which is available with windows 10
[Uploading Memory leak.zip…](memory leak steps)

**Comment by parrt** [comment]
Any ideas @bjansen ?

**Comment by bjansen** [comment]
@kiranmohantp I can't see the screenshots. Is the IDE still responding, or does it freeze like in #393?
@parrt could it be a bad grammar that makes the interpreter allocate lots of objects maybe?

**Comment by kiranmohantp** [comment]
@bjansen it freezes and stopped responding.

**Comment by bjansen** [comment]
While using the Preview window?

**Comment by kiranmohantp** [comment]
@bjansen yes

And I do not think it is because of bad grammar, because now it is working fine for the same grammar

**Comment by bjansen** [comment]
Could you go to Help > Show Log and attach one of the folders named `threadDumps-freeze-xxx` that was created during the freeze please?

**Comment by kiranmohantp** [comment]
[threadDumps-freeze-20200226-233401-IC-191.7479.19.zip](https://github.com/antlr/intellij-plugin-v4/files/4257858/threadDumps-freeze-20200226-233401-IC-191.7479.19.zip)

**Comment by bjansen** [comment]
Relevant stack traces:

```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:265)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
	at java.util.ArrayList.add(ArrayList.java:462)
	at org.antlr.v4.runtime.ParserRuleContext.addAnyChild(ParserRuleContext.java:134)
	at org.antlr.v4.runtime.ParserRuleContext.addChild(ParserRuleContext.java:145)
	at org.antlr.v4.runtime.Parser.consume(Parser.java:584)
	at org.antlr.v4.runtime.Parser.match(Parser.java:203)
	at org.antlr.intellij.plugin.parsing.PreviewParser.match(PreviewParser.java:64)
	at org.antlr.v4.runtime.ParserInterpreter.visitState(ParserInterpreter.java:246)
	at org.antlr.v4.runtime.ParserInterpreter.parse(ParserInterpreter.java:194)
	at org.antlr.intellij.plugin.parsing.ParsingUtils.parseText(ParsingUtils.java:313)
	at org.antlr.intellij.plugin.parsing.ParsingUtils.parseText(ParsingUtils.java:271)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.parseText(ANTLRv4PluginController.java:437)
	at org.antlr.intellij.plugin.preview.PreviewPanel.updateParseTreeFromDoc(PreviewPanel.java:313)
```
or
```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

	at java.util.regex.Matcher.<init>(Matcher.java:226)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at java.lang.String.replace(String.java:2239)
	at org.antlr.v4.runtime.DefaultErrorStrategy.escapeWSAndQuote(DefaultErrorStrategy.java:644)
	at org.antlr.v4.runtime.DefaultErrorStrategy.getTokenErrorDisplay(DefaultErrorStrategy.java:629)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportMissingToken(DefaultErrorStrategy.java:406)
	at org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenInsertion(DefaultErrorStrategy.java:519)
	at org.antlr.v4.runtime.DefaultErrorStrategy.recoverInline(DefaultErrorStrategy.java:476)
	at org.antlr.v4.runtime.Parser.match(Parser.java:206)
	at org.antlr.intellij.plugin.parsing.PreviewParser.match(PreviewParser.java:64)
	at org.antlr.v4.runtime.ParserInterpreter.visitState(ParserInterpreter.java:246)
	at org.antlr.v4.runtime.ParserInterpreter.parse(ParserInterpreter.java:194)
	at org.antlr.intellij.plugin.parsing.ParsingUtils.parseText(ParsingUtils.java:313)
	at org.antlr.intellij.plugin.parsing.ParsingUtils.parseText(ParsingUtils.java:271)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.parseText(ANTLRv4PluginController.java:437)
	at org.antlr.intellij.plugin.preview.PreviewPanel.updateParseTreeFromDoc(PreviewPanel.java:313)
```

or

```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

	at org.antlr.v4.runtime.DefaultErrorStrategy.getErrorRecoverySet(DefaultErrorStrategy.java:744)
	at org.antlr.v4.runtime.DefaultErrorStrategy.recover(DefaultErrorStrategy.java:179)
	at org.antlr.v4.runtime.ParserInterpreter.recover(ParserInterpreter.java:404)
	at org.antlr.v4.runtime.ParserInterpreter.parse(ParserInterpreter.java:200)
	at org.antlr.intellij.plugin.parsing.ParsingUtils.parseText(ParsingUtils.java:313)
	at org.antlr.intellij.plugin.parsing.ParsingUtils.parseText(ParsingUtils.java:271)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.parseText(ANTLRv4PluginController.java:437)
	at org.antlr.intellij.plugin.preview.PreviewPanel.updateParseTreeFromDoc(PreviewPanel.java:313)
```

The interpreter is definitely stuck somewhere. Do you see warnings in your grammar? Do you have something like `EOF*` somewhere?

**Comment by kiranmohantp** [comment]
Nothing like EOF* in my grammar . But even If I have something like that in my grammar can we have some kind of mechanism to prevent IDE from crashing because error from user side is really common right.

**Comment by karthikapurushothaman** [comment]
@kiranmohantp any luck??

**Comment by bjansen** [comment]
Version 1.15 introduced a new mechanism that should prevent this kind of crashes, when the interpreter is stuck in a loop:

https://github.com/antlr/intellij-plugin-v4/releases/tag/1.15

I'll close the issue, but feel free to reopen it if you're still experiencing problems in the latest version.
