### ISSUE TITLE
null pointer exception when IDEA 2016.3 opens ANTLR Project

### ISSUE THREAD

**Issue by awhawks** [antlr/intellij-plugin-v4#290]
my IDEA version is 

IntelliJ IDEA 2016.3.1
Build #IU-163.9166.29, built on December 9, 2016
...
...
JRE: 1.8.0_112-release-408-b2 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

the plugin version is 1.8.3 DEC 20 2016 version

I'm trying to learn Antlr for a project I'm working on and am in the process of trying to create a grammar for PowerBasic

The grammar is at any given time valid and when I get it wrong invalid.
I think the invalid part of my grammar is a statement I've just added.

stmt_DEFLNG : KW_DEFLNG ('A'..'Z' | ('A'..'Z') MINUS ('A'..'Z')) (COMMA ('A'..'Z' | ('A'..'Z') MINUS ('A'..'Z')))* ;

If I remove the above statement and rule references to it the error does not happen.
I've attached the .g4 grammar as it is. 
[PowerBasic.g4.txt](https://github.com/antlr/intellij-plugin-v4/files/665701/PowerBasic.g4.txt)

`null
java.lang.NullPointerException
	at org.antlr.v4.automata.ParserATNFactory.elemList(ParserATNFactory.java:481)
	at org.antlr.v4.automata.ParserATNFactory.alt(ParserATNFactory.java:450)
	at org.antlr.v4.parse.ATNBuilder.alternative(ATNBuilder.java:557)
	at org.antlr.v4.parse.ATNBuilder.ruleBlock(ATNBuilder.java:291)
	at org.antlr.v4.automata.ParserATNFactory._createATN(ParserATNFactory.java:161)
	at org.antlr.v4.automata.ParserATNFactory.createATN(ParserATNFactory.java:108)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:389)
	at org.antlr.v4.Tool.process(Tool.java:362)
	at org.antlr.intellij.plugin.parsing.ParsingUtils.loadGrammars(ParsingUtils.java:369)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.updateGrammarObjectsFromFile_(ANTLRv4PluginController.java:362)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.updateGrammarObjectsFromFile(ANTLRv4PluginController.java:346)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.currentEditorFileChangedEvent(ANTLRv4PluginController.java:283)
	at org.antlr.intellij.plugin.ANTLRv4PluginController$MyFileEditorManagerAdapter.selectionChanged(ANTLRv4PluginController.java:552)
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:381)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:368)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:354)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:347)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
	at com.sun.proxy.$Proxy90.selectionChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:1580)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$9$1.run(FileEditorManagerImpl.java:1057)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:646)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.m(FocusManagerImpl.java:630)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.p(FocusManagerImpl.java:600)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.b(FocusManagerImpl.java:482)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2493)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:462)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:457)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:70)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$9.run(FileEditorManagerImpl.java:1054)
	at com.intellij.openapi.util.BusyObject$Impl$Simple.execute(BusyObject.java:123)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.notifyPublisher(FileEditorManagerImpl.java:1050)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.fireSelectionChanged(FileEditorManagerImpl.java:1580)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.a(EditorsSplitters.java:624)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.setCurrentWindow(EditorsSplitters.java:633)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.setEditor(EditorWindow.java:687)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:918)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:930)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:207)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:435)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:338)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:342)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:321)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:193)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:403)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:188)
	at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:60)
	at com.intellij.ide.ReopenProjectAction.actionPerformed(ReopenProjectAction.java:68)
	at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$2.onClick(RecentProjectPanel.java:126)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$MyList.processMouseEvent(RecentProjectPanel.java:347)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by parrt** [comment]
Looks like an antlr tool not plugin issue. The "Tool output" should show:

```
beast:/tmp $ a4.6 PowerBasic.g4 
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
error(20): PowerBasic.g4:18:14: internal error: Rule perfectSyncCommands undefined 
error(20):  internal error: element list has first|last == null 
Exception in thread "main" java.lang.NullPointerException
	at org.antlr.v4.automata.ParserATNFactory.elemList(ParserATNFactory.java:481)
	at org.antlr.v4.automata.ParserATNFactory.alt(ParserATNFactory.java:450)
	at org.antlr.v4.parse.ATNBuilder.alternative(ATNBuilder.java:557)
	at org.antlr.v4.parse.ATNBuilder.ruleBlock(ATNBuilder.java:291)
	at org.antlr.v4.automata.ParserATNFactory._createATN(ParserATNFactory.java:161)
	at org.antlr.v4.automata.ParserATNFactory.createATN(ParserATNFactory.java:108)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:389)
	at org.antlr.v4.Tool.process(Tool.java:362)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:321)
	at org.antlr.v4.Tool.main(Tool.java:168)
```
