### ISSUE TITLE
Another null ptr for "show lookahead trees"

### ISSUE THREAD

**Issue by parrt** [antlr/intellij-plugin-v4#291]
```
java.lang.NullPointerException
	at org.antlr.v4.runtime.tree.Trees.findNodeSuchThat(Trees.java:252)
	at org.antlr.intellij.plugin.parsing.ParsingUtils.findOverriddenDecisionRoot(ParsingUtils.java:492)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog.setTrees(ShowAmbigTreesDialog.java:227)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog.popupAmbigTreesDialog(ShowAmbigTreesDialog.java:126)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog$3.run(ShowAmbigTreesDialog.java:84)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1392)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by parrt** [comment]
Added null check in antlr, which got pulled in for 1.8.4.
