### ISSUE TITLE
antlr can't process .g4

### ISSUE THREAD

**Issue by trrao** [antlr/intellij-plugin-v4#317]
antlr can't process allobjects.g4

```
java.lang.NullPointerException
	at org.antlr.v4.analysis.LeftRecursiveRuleAnalyzer.getArtificialOpPrecRule(LeftRecursiveRuleAnalyzer.java:211)
	at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.translateLeftRecursiveRule(LeftRecursiveRuleTransformer.java:116)
	at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.translateLeftRecursiveRules(LeftRecursiveRuleTransformer.java:71)
	at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:71)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:375)
	at org.antlr.v4.Tool.process(Tool.java:362)
	at org.antlr.intellij.plugin.ANTLRv4ExternalAnnotator.doAnnotate(ANTLRv4ExternalAnnotator.java:112)
	at org.antlr.intellij.plugin.ANTLRv4ExternalAnnotator.doAnnotate(ANTLRv4ExternalAnnotator.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.c(ExternalToolPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:47)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:158)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This was reported at the start of PyCharm IDE Antlr4 Plugin.

**Comment by parrt** [comment]
Can you give us a sample grammar that causes this?

**Comment by bjansen** [comment]
I was able to reproduce this by specifying an incorrect language in the "Configure ANTLR..." dialog.
As a result, `org.antlr.v4.analysis.LeftRecursiveRuleAnalyzer#codegenTemplates` is null because no ST templates were found for this language.

**Comment by bjansen** [comment]
I fixed the problem by using the default target language when the one configured in the dialog does not exist. I also added a warning in the editor to make it clear that there is a problem:

![image](https://user-images.githubusercontent.com/281528/53765843-6d0a7680-3ed1-11e9-8a60-3a61bc9c7fca.png)

The same exception happens when I call the `Generate ANTLR Recognizer` action, but I think I'm not going to fix it, because the tool already reports the bad configuration:

```
error(31):  ANTLR cannot generate Lol code as of version 4.7.2
2019-03-04 23:01:52: antlr4 java.lang.NullPointerException
	at org.antlr.v4.analysis.LeftRecursiveRuleAnalyzer.getArtificialOpPrecRule(LeftRecursiveRuleAnalyzer.java:211)
	at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.translateLeftRecursiveRule(LeftRecursiveRuleTransformer.java:116)
	at org.antlr.v4.analysis.LeftRecursiveRuleTransformer.translateLeftRecursiveRules(LeftRecursiveRuleTransformer.java:71)
...
```
