### ISSUE TITLE
Exception when showing phrase interpretations

### ISSUE THREAD

**Issue by hackathlete** [antlr/intellij-plugin-v4#319]
I get following index out of bound exception when I want to display all phrase interpretations of an ambiguity:

```
Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog.mark(ShowAmbigTreesDialog.java:271)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog.setTrees(ShowAmbigTreesDialog.java:239)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog.popupAmbigTreesDialog(ShowAmbigTreesDialog.java:126)
	at org.antlr.intellij.plugin.preview.ShowAmbigTreesDialog$3.run(ShowAmbigTreesDialog.java:84)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.ui.popup.AbstractPopup.lambda$null$8(AbstractPopup.java:1428)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by parrt** [comment]
Can you give me a simple grammar that causes this?

**Comment by bjansen** [comment]
I think I fixed the problem.
