### ISSUE TITLE
After installing the plug-in can't start the Idea

### ISSUE THREAD

**Issue by mojita** [antlr/intellij-plugin-v4#341]
class with name 'org.antlr.intellij.plugin.actions.InlineRuleAction' not found [Plugin: org.antlr.intellij.plugin]

class with name 'org.antlr.intellij.plugin.actions.InlineRuleAction' not found [Plugin: org.antlr.intellij.plugin]
com.intellij.diagnostic.PluginException: class with name 'org.antlr.intellij.plugin.actions.InlineRuleAction' not found [Plugin: org.antlr.intellij.plugin]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:194)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:156)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:486)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:474)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1244)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:32)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.antlr.intellij.plugin.actions.InlineRuleAction PluginClassLoader[org.antlr.intellij.plugin, 1.8.4] com.intellij.ide.plugins.cl.PluginClassLoader@6f300563
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:152)
	... 15 more

# IDEA VERSION 2017.3
# MACOS
# JDK 1.8

**Comment by parrt** [comment]
that's weird. looks like it's missing `org.antlr.intellij.*` classes. did you install with plugin manager?

**Comment by parrt** [comment]
Duplicated of #338

**Comment by bjansen** [comment]
@mojita could you try with the latest version (1.9)?

**Comment by bjansen** [comment]
Closing, feel free to reopen if you still have the problem after upgrading to 1.9 or 1.10.
