### ISSUE TITLE
StackOverflowError raised from GoLand 

### ISSUE THREAD

**Issue by PeterBocan** [antlr/intellij-plugin-v4#354]
ANTRL v4 grammar plugin (v1.9) raises following exception from within GoLand 2019.1 

```
java.lang.StackOverflowError
	at org.antlr.v4.runtime.atn.LexerATNSimulator.getEpsilonTarget(LexerATNSimulator.java:475)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:456)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
        ...
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
```

**Comment by bjansen** [comment]
Does it happen with any kind of grammar? 
Does it also happen if you run the antlr tool directly on this grammar?

`LexerATNSimulator` is not part of the IntelliJ plugin, but comes from ANTLRv4, so I suspect it's either something wrong in your grammar, or a bug in ANTLR.

**Comment by bjansen** [comment]
Your problem looks very much like https://github.com/antlr/antlr4/issues/1943

**Comment by bjansen** [comment]
Please see one of the issues mentioned above to get more info on the problem.
