### ISSUE TITLE
NPE when trying to specify start rule

### ISSUE THREAD

**Issue by Stranger2015** [antlr/intellij-plugin-v4#356]
java.lang.NullPointerException
	at org.antlr.intellij.plugin.preview.JTreeViewer.selectNodeAtOffset(JTreeViewer.java:149)
	at org.antlr.intellij.plugin.preview.InputPanel.setCursorToHierarchyViewElement(InputPanel.java:730)
	at org.antlr.intellij.plugin.preview.PreviewEditorMouseListener.mouseClicked(PreviewEditorMouseListener.java:53)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseClickedCommand(EditorImpl.java:3796)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:3723)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by bjansen** [comment]
It looks like the same problem as https://github.com/antlr/intellij-plugin-v4/issues/268. Do you remember which actions led to this NPE by any chance?

**Comment by Stranger2015** [comment]
Tried to specify the start rule

HiLogParser.g4.txt](https://github.com/antlr/intellij-plugin-v4/files/3225454/HiLogParser.g4.txt)
[HiLogLexer.g4.txt](https://github.com/antlr/intellij-plugin-v4/files/3225461/HiLogLexer.g4.txt)

**Comment by Stranger2015** [comment]
I 've attached 2 files  as the grammar sources

**Comment by clojj** [comment]
@Stranger2015 I don't get it.. having both attached grammars (lexer + parser), I can't find the definition for many terms... like 
`variable : (ANONYMOUS_VARIABLE|NAMED_VARIABLE);`

Where is the definition of NAMED_VARIABLE ?

**Comment by Stranger2015** [comment]
NAMED_VARIABLE : ([A-Z]|'_')+ ([a-z]|[A-Z]|[0-9]|'_')*;

**Comment by clojj** [comment]
Does the IJ plugin support separated lexer / parser ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Stranger2015** [comment]
yes it supports.
btw. **UNDERBAR** in my comment means "_".
__NAMED_VAR__ is the following:
the front char is the uppercase letter or underbar char. The remaining chars are any letter or digit or underbar. 
__ANONYMOUS_VARIABLE__ are designated with single underbar which means that they are distinct vars (place holders) and their names are out of interest.

**Comment by clojj** [comment]
![antlr-lex-parse-test](https://user-images.githubusercontent.com/4367963/60169692-795f6a00-9807-11e9-9d36-3a9da124f0fc.png)

so I have this setup and get these error messages
the ANONYMOUS_VARIABLE is not defined anywhere in the 2 files you attachede here, isn't it ?

**Comment by Stranger2015** [comment]
Yes, it is... I'm sorry about that

variable:
    NAMED_VARIABLE |
    ANONYMOUS_VARIABLE
    ;

fragment NAMED_VARIABLE :
    ( UPPER_LETTER ( ALPHA_NUM | UNDERSCORE )*? ) | //zero or more
    ( UNDERSCORE ( UPPER_LETTER | ALPHA_NUM | UNDERSCORE )+ ) // one or more 
 ;

fragment ANONYMOUS_VARIABLE :
    UNDERSCORE
 ;
fragment ALPHA_NUM: 
    ALPHA | DIGIT 
;
fragment ALPHA:
    UPPER_LETTER | LOWER_LETTER
;

**Comment by clojj** [comment]
and having HiLogLexer.g4 and HiLogParser.g4 side-by-side, you can successfully "Test Rule variable" ?
I don't get it. Can you attach the 2 complete g4 files again, maybe they are incomplete.. ?

Or it is a misunderstanding between us.
Do I have to generate something first ? or chosse some other directory layout ?

**Comment by clojj** [comment]
also this... it just won' recognize the definitions
![nb3](https://user-images.githubusercontent.com/4367963/60178937-d87ba980-981c-11e9-8187-5327c033e1ac.png)

**Comment by clojj** [comment]
ok, just tested 'separated lexer + parser' feature with this example:
https://github.com/antlr/grammars-v4/tree/master/wat

all is good, never mind... thanks for your help

**Comment by bjansen** [comment]
I was able to reproduce the error. I copied your two grammar files, reopened the project, selected a start rule, enabled "Scroll from source" in the Hierarchy view, typed random text in the preview editor then clicked somewhere inside that text. This throws the NPE.
