### ISSUE TITLE
The plugin stopped working, throwing exceptions

### ISSUE THREAD

**Issue by AlexiyOrlov** [antlr/intellij-plugin-v4#357]
I have separated lexer and parser rules, Everything worked fine until today. Whenever I try to test a parser rule, it's throwing exceptions which I can see from blinking error icon of Idea. Here are exceptions:
1.
```
java.lang.StackOverflowError
	at org.antlr.v4.runtime.misc.MurmurHash.update(MurmurHash.java:71)
	at org.antlr.v4.runtime.atn.LexerATNConfig.hashCode(LexerATNConfig.java:78)
	at org.antlr.v4.runtime.misc.ObjectEqualityComparator.hashCode(ObjectEqualityComparator.java:29)
	at org.antlr.v4.runtime.misc.Array2DHashSet.getBucket(Array2DHashSet.java:108)
	at org.antlr.v4.runtime.misc.Array2DHashSet.getOrAddImpl(Array2DHashSet.java:63)
	at org.antlr.v4.runtime.misc.Array2DHashSet.getOrAdd(Array2DHashSet.java:59)
	at org.antlr.v4.runtime.atn.ATNConfigSet.add(ATNConfigSet.java:146)
	at org.antlr.v4.runtime.atn.ATNConfigSet.add(ATNConfigSet.java:122)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:449)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)

```

2.
```
java.lang.StackOverflowError
	at org.antlr.v4.runtime.atn.ATNConfigSet.add(ATNConfigSet.java:122)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:449)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
```
3.
```
java.lang.StackOverflowError
	at org.antlr.v4.runtime.misc.Array2DHashSet.getBucket(Array2DHashSet.java:108)
	at org.antlr.v4.runtime.misc.Array2DHashSet.getOrAddImpl(Array2DHashSet.java:63)
	at org.antlr.v4.runtime.misc.Array2DHashSet.getOrAdd(Array2DHashSet.java:59)
	at org.antlr.v4.runtime.atn.ATNConfigSet.add(ATNConfigSet.java:146)
	at org.antlr.v4.runtime.atn.ATNConfigSet.add(ATNConfigSet.java:122)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:449)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
```
4.
```
java.lang.StackOverflowError
	at org.antlr.v4.runtime.misc.Array2DHashSet.getOrAdd(Array2DHashSet.java:59)
	at org.antlr.v4.runtime.atn.ATNConfigSet.add(ATNConfigSet.java:146)
	at org.antlr.v4.runtime.atn.ATNConfigSet.add(ATNConfigSet.java:122)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:449)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:458)
```

"Invalidate and restart" doesn't help.

**Comment by bjansen** [comment]
It's not the exact same stack trace as #354 but it seems to involve a lot of `LexerATNSimulator.java:458` as well. 
I think your errors are not caused by the plugin itself, but by the ANTLR tool, see https://github.com/antlr/antlr4/issues/1943 and https://github.com/antlr/antlr4/issues/1105.

**Comment by bjansen** [comment]
Please refer to the aforementioned issues to track progress on fixes.
