### ISSUE TITLE
java.lang.IllegalStateException: Already disposed: Project

### ISSUE THREAD

**Issue by turbanoff** [antlr/intellij-plugin-v4#386]
After I closed project got this exception from:

```
org.antlr.intellij.plugin.ANTLRv4PluginController@163b4c1b

java.lang.IllegalStateException: Already disposed: Project (name=dxmc, containerState=DISPOSE_IN_PROGRESS, componentStore=D:\Projects\dxmc) 
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getMessageBus(PlatformComponentManagerImpl.kt:90)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.uninstallListeners(ANTLRv4PluginController.java:179)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.projectClosed(ANTLRv4PluginController.java:158)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectClosed(ProjectManagerImpl.java:849)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$closeProject$13(ProjectManagerImpl.java:729)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:859)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:722)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.java:753)
	at com.intellij.openapi.wm.impl.CloseProjectWindowHelper.closeProjectAndShowWelcomeFrameIfNoProjectOpened(CloseProjectWindowHelper.kt:44)
	at com.intellij.openapi.wm.impl.CloseProjectWindowHelper.windowClosing(CloseProjectWindowHelper.kt:32)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper$2.windowClosing(ProjectFrameHelper.java:231)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
	at java.desktop/java.awt.Window.processWindowEvent(Window.java:2079)
	at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
	at java.desktop/java.awt.Window.processEvent(Window.java:2038)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:933)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:806)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:433)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:690)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:432)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Antlr plugin v1.13.1

IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.3803.71, built on January 24, 2020
IntelliJ IDEA EAP User
Expiration date: February 23, 2020
Runtime version: 11.0.5+9-b674.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 8.1 6.3
GC: ParNew, ConcurrentMarkSweep
Memory: 2466M
Cores: 4
Registry: debugger.emulate.method.breakpoints=false, undo.documentUndoLimit=300, analyze.exceptions.on.the.fly=true
Non-Bundled Plugins: com.bulenkov.idea.Idea11Icons, GrepConsole, Jetbrains TeamCity Plugin, org.turbanov.dxcore.inspections, org.antlr.intellij.plugin, org.turbanov.execution.cmd, org.nik.presentation-assistant, org.turbanov.commits.message.checker, org.turbanov.run.configuration.as.action

**Comment by bjansen** [comment]
Thanks for reporting the problem.

**Comment by ice1000** [comment]
Similarly:

```
org.antlr.intellij.plugin.ANTLRv4PluginController@35266188

java.lang.IllegalStateException: Already disposed: Project (name=arend, containerState=DISPOSE_IN_PROGRESS, componentStore=C:\Users\ice10\git-repos\Arend\Arend) 
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getMessageBus(PlatformComponentManagerImpl.kt:98)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.uninstallListeners(ANTLRv4PluginController.java:179)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.projectClosed(ANTLRv4PluginController.java:158)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectClosed(ProjectManagerImpl.java:847)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$closeProject$13(ProjectManagerImpl.java:727)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:865)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:720)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.java:751)
	at com.intellij.openapi.wm.impl.CloseProjectWindowHelper.closeProjectAndShowWelcomeFrameIfNoProjectOpened(CloseProjectWindowHelper.kt:44)
	at com.intellij.openapi.wm.impl.CloseProjectWindowHelper.windowClosing(CloseProjectWindowHelper.kt:32)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper$2.windowClosing(ProjectFrameHelper.java:233)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
	at java.desktop/java.awt.Window.processWindowEvent(Window.java:2079)
	at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
	at java.desktop/java.awt.Window.processEvent(Window.java:2038)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:933)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:806)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:433)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:713)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:432)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by ice1000** [comment]
This happens very very frequently. Can we have an intermediate version released that includes this fix?

**Comment by bjansen** [comment]
Sure, I just release v1.14 which contains a fix for this issue.

**Comment by ice1000** [comment]
Thanks!
