### ISSUE TITLE
NPE during grammar generation

### ISSUE THREAD

**Issue by bjansen** [antlr/intellij-plugin-v4#387]
```
java.lang.NullPointerException
	at org.antlr.intellij.plugin.parsing.RunANTLROnGrammarFile.getANTLRArgs(RunANTLROnGrammarFile.java:224)
	at org.antlr.intellij.plugin.parsing.RunANTLROnGrammarFile.getANTLRArgsAsList(RunANTLROnGrammarFile.java:178)
	at org.antlr.intellij.plugin.parsing.RunANTLROnGrammarFile.antlr(RunANTLROnGrammarFile.java:131)
	at org.antlr.intellij.plugin.parsing.RunANTLROnGrammarFile.run(RunANTLROnGrammarFile.java:78)
```

There's no `encoding` option in `misc.xml` for this grammar:

```
        <PerGrammarGenerationSettings>
          <option name="fileName" value="$PROJECT_DIR$/parser/src/main/antlr/com/github/bjansen/pebble/parser/PebbleParser.g4" />
          <option name="outputDir" value="$PROJECT_DIR$/parser/build/generated-src/antlr/main" />
          <option name="pkg" value="com.github.bjansen.pebble.parser" />
          <option name="language" value="Java" />
          <option name="generateListener" value="false" />
          <option name="generateVisitor" value="true" />
        </PerGrammarGenerationSettings>
```

Opening and saving the grammar properties will add two new options:
```
          <option name="libDir" value="" />
          <option name="encoding" value="" />
```

**Comment by bjansen** [comment]
This was fixed in a5a9a24bfbe7380c571513b9a748a5106829b56b.
