### ISSUE TITLE
Plugin exception

### ISSUE THREAD

**Issue by ice1000** [antlr/intellij-plugin-v4#404]
IDE: IC-202.6397.59
OS: Windows 10 2004

Stacktrace:

```
ExternalToolPass: 

com.intellij.diagnostic.PluginException: annotator: org.antlr.intellij.plugin.ANTLRv4ExternalAnnotator@76648048 (class org.antlr.intellij.plugin.ANTLRv4ExternalAnnotator) [Plugin: org.antlr.intellij.plugin]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:290)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:58)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.process(ExternalToolPass.java:256)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doApply(ExternalToolPass.java:221)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$700(ExternalToolPass.java:41)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$1(ExternalToolPass.java:185)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:869)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:51)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:182)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:251)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:180)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:287)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:242)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:356)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:215)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:194)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:183)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at org.antlr.intellij.plugin.preview.PreviewPanel.autoRefreshPreview(PreviewPanel.java:349)
	at org.antlr.intellij.plugin.ANTLRv4ExternalAnnotator.apply(ANTLRv4ExternalAnnotator.java:56)
	at org.antlr.intellij.plugin.ANTLRv4ExternalAnnotator.apply(ANTLRv4ExternalAnnotator.java:24)
	at com.intellij.codeInsight.daemon.impl.AnnotationHolderImpl.applyExternalAnnotatorWithContext(AnnotationHolderImpl.java:205)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doApply(ExternalToolPass.java:218)
	... 37 more
```

**Comment by bjansen** [comment]
What version of the plugin are you using?

`PreviewPanel.java:349` has an `if` statement on a `boolean`, I don't see how this could throw a NPE.

**Comment by ice1000** [comment]
I guess it's the latest release. Can you kindly please check the release version of the source code?

**Comment by bjansen** [comment]
I checked the release version, and I don't understand how it could throw an exception. Do you see plugin updates when you go to `Help | Check for Updates`?

**Comment by ice1000** [comment]
Hi, the version I saw is 1.14.

**Comment by ice1000** [comment]
I guess the exception is raised in this line:

https://github.com/antlr/intellij-plugin-v4/blob/1b8aac4918fcbce0b932073875e6548eb5daddbd/src/main/java/org/antlr/intellij/plugin/preview/PreviewPanel.java#L351

Maybe check for NPE here?
Btw, you can enable `instrumentCode` provided by the gradle-intellij-plugin to make the error message more helpful.

**Comment by ice1000** [comment]
Related to #413

**Comment by bjansen** [comment]
Updated stack trace taken from #435:

```
Caused by: java.lang.NullPointerException
at org.antlr.intellij.plugin.preview.PreviewPanel.autoRefreshPreview(PreviewPanel.java:358)
at org.antlr.intellij.plugin.ANTLRv4ExternalAnnotator.apply(ANTLRv4ExternalAnnotator.java:56)
at org.antlr.intellij.plugin.ANTLRv4ExternalAnnotator.apply(ANTLRv4ExternalAnnotator.java:24)
at com.intellij.codeInsight.daemon.impl.AnnotationHolderImpl.applyExternalAnnotatorWithContext(AnnotationHolderImpl.java:203)
at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doApply(ExternalToolPass.java:217)
... 37 more
```
