### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by geniot** [antlr/intellij-plugin-v4#463]
No specific action was taken. I even didn't use the plugin, just opened a new project.

java.lang.StackOverflowError
	at org.antlr.v4.runtime.atn.LexerATNSimulator.getEpsilonTarget(LexerATNSimulator.java:472)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.closure(LexerATNSimulator.java:453)

**Comment by bjansen** [comment]
Hi @geniot. This is a known issue that happens to be caused by ANTLR itself, see https://github.com/antlr/antlr4/issues/1943. Since there's nothing much we can do on the plugin side, I suggest you subscribe to this other issue instead.
