### ISSUE TITLE
Can't load group file antlr.stg

### ISSUE THREAD

**Issue by gfour** [antlr/intellij-plugin-v4#481]
I am getting a crash and a gray/unusable ANTLR preview when opening C.g4 from the grammars-v4 repo (https://github.com/antlr/grammars-v4/blob/master/c/C.g4).

idea.log reports the following:
```
STDERR - can't load group file jar:file:/:/var/lib/flatpak/exports/share/JetBrains/IdeaIC2021.2/antlr-intellij-plugin-v4/lib/antlr4-4.9.1.jar!/org/antlr/v4/tool/templates/messages/formats/antlr.stg 
STDERR - Caused by: java.nio.file.NoSuchFileException: /:/var/lib/flatpak/exports/share/JetBrains/IdeaIC2021.2/antlr-intellij-plugin-v4/lib/antlr4-4.9.1.jar 
...
STDERR - 	at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155) 
STDERR - 	at java.base/java.net.URL.openStream(URL.java:1165) 
STDERR - 	at org.stringtemplate.v4.STGroup.loadGroupFile(STGroup.java:673) 
STDERR - 	at org.stringtemplate.v4.STGroupFile.load(STGroupFile.java:147) 
STDERR - 	at org.antlr.v4.tool.ErrorManager.setFormat(ErrorManager.java:235) 
STDERR - 	at org.antlr.v4.Tool.<init>(Tool.java:200) 
STDERR - 	at org.antlr.intellij.plugin.validation.GrammarIssuesCollector.collectGrammarIssues(GrammarIssuesCollector.java:52) 
```

I am using IntelliJ IDEA 2021.2.2 (Community Edition), which is indeed not mentioned as supported in the README. Is this a known issue?

This happens with both the latest stable (1.16) and compiled-from-source (1.17-SNAPSHOT) versions of the plugin.

**Comment by gfour** [comment]
Thanks for the quick reply! These errors started to appear since (auto-)updating the IDE via Ubuntu snap and I've since seen `:` directories created. For example:
```
$ ls ${HOME}/.config/JetBrains/                                                       
:  IdeaIC2021.2
$ ls ${HOME}/.config/JetBrains/:/var/lib/flatpak/exports/share/JetBrains/IdeaIC2021.2/
brokenPlugins.json  brokenPlugins.json.etag  devkit-helper.jar  jsToolbox.jar  meta  pluginsXMLIds.json  pluginsXMLIds.json.etag  python-ce
```
(Deleting this `:` directory makes the IDE lose installed plugins and re-create the directory on IDE restart.)

**Comment by gfour** [comment]
Update: this error goes away if I unset environment variables `XDG_DATA_HOME`/`XDG_DATA_DIRS` (https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). This was probably due to a malformed `XDG_DATA_HOME` value (containing a colon character seems to be a problem for the IDE). I am closing this issue.
