### ISSUE TITLE
Exception after bad input pane editing in ANTLR preview

### ISSUE THREAD

**Issue by parrt** [antlr/intellij-plugin-v4#500]
ANTLR PLUGIN 1.17 which is pretty out of date with ANTLR. It has 4.9.1 not 4.9.3.

Intellij:

```
IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Build #IU-213.6777.52, built on January 27, 2022
Runtime version: 11.0.13+7-b1751.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
```

1. Download this grammar [Malloy.g4](https://github.com/looker-open-source/malloy/blob/main/packages/malloy/src/lang/grammar/Malloy.g4)
1. open in fresh intellij w/o project.
1. right click on first rule `malloyDocument`
2. Paste `import "hackernews.malloy"` into input window of ANTLR preview; tree created properly
3. Click on input text in `"..."` anywhere and it seems to select/highlight that whole string.
4. Click to left of `w` and delete that char. Now it highlights til right edge of line
5. Click delete one more time and whole string to end of line disappears leaving `import `

Undo all those changes and see another sequence

1. Click after `.` and it highlights string.
2. Hit delete button and whole string disappears again. 
3. I undid and clicked again in same spot

That just gave me exception in the gui code:

```
java.lang.Throwable: Wrong endOffset: 26, textLength=8
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.openapi.editor.impl.CaretImpl.lambda$doSetSelection$6(CaretImpl.java:1081)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:421)
	at com.intellij.openapi.editor.impl.CaretImpl.doSetSelection(CaretImpl.java:1068)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1031)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1026)
	at com.intellij.openapi.editor.SelectionModel.setSelection(SelectionModel.java:155)
	at org.antlr.intellij.plugin.preview.PreviewPanel.onParserRuleSelected(PreviewPanel.java:508)
	at org.antlr.intellij.plugin.preview.HierarchyViewer.valueChanged(HierarchyViewer.java:159)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:2967)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:619)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.clearSelection(DefaultTreeSelectionModel.java:580)
	at java.desktop/javax.swing.JTree.clearSelection(JTree.java:2701)
	at java.desktop/javax.swing.JTree.setModel(JTree.java:861)
	at org.antlr.intellij.plugin.preview.HierarchyViewer.setTree(HierarchyViewer.java:63)
	at org.antlr.intellij.plugin.preview.PreviewPanel.lambda$clearTabs$1(PreviewPanel.java:363)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by parrt** [comment]
Interesting.  Launching from intellij in sandbox, the 2019.1.3 CE doesn't have this problem:

```
IntelliJ IDEA 2019.1.3 (Community Edition)
Build #IC-191.7479.19, built on May 27, 2019
JRE: 1.8.0_202-release-1483-b53 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
```

Wow. It thinks it's on 10.16? I'm on 12.0.1 OS X.
