### ISSUE TITLE
Exception ANTLR4 1.17 in IntelliJ

### ISSUE THREAD

**Issue by JoshuaCrotts** [antlr/intellij-plugin-v4#507]
**Description:**
This bug seems to happen rather arbitrarily when copying and pasting test input into the ANTLR Preview box. I imagine it's because of the Tree preview box, but other than that, I really have no idea what causes it. The `startOffset` number seems to change randomly when altering the input and zooming in/out of the preview. I've tried to minimize the grammar as much as possible.

**Grammar:**
```
grammar MicroScheme;
WHITESPACE: [ \r\n\t]+ -> skip;
COMMENT: ';' (.)*? NEWLINE -> skip; // Match any text that has ; preceding.
fragment DIGIT: [0-9];
fragment UPPER_CASE_LTR: [a-z];
fragment LOWER_CASE_LTR: [A-Z];
fragment ANY_CASE_LTR: [a-zA-Z];
fragment UNDERSCORE: '_';
fragment QUOTCHAR: '\\' .;
fragment DOUBLE_QUOTE: '"';
fragment ANYCHAR: .;
fragment NEWLINE: '\n';
fragment CARRIAGE_RET: '\r';
fragment TAB: '\t';
fragment NULL_CHAR: '\\0';
fragment ESCAPED_CHAR: ('\\' .);
fragment ANYCHAR_MOD: (.+?);

// Arbitrary tokens.
OPEN_PAREN: '(';
CLOSE_PAREN: ')';
OPEN_BRACKET: '[';
CLOSE_BRACKET: ']';
SINGLE_QUOTE: '\'';
BACK_TICK: '`';
COMMA: ',';
HASH: '#';
PERIOD: '.';

// Literals.
NUMBERLIT: [-]?[0-9]+('.'[0-9]*)?([+-]?[0-9]+('.'[0-9]*)?[Ii])?;
STRINGLIT: '"' ( QUOTCHAR | ~ ["\\] )* '"';
CHARLIT: HASH '\\' ANYCHAR_MOD;
BOOLLIT: HASH ([tf] | ([Tt]'rue') | ([Ff]'alse'));

// Special keywords.
DEFINE: 'define' | 'DEFINE';
IF:  'if' | 'IF';
COND: 'cond' | 'COND';
ELSE: 'else' | 'ELSE';
LAMBDA: 'lambda' | 'LAMBDA' | 'λ';
QUOTE: 'quote' | 'QUOTE';

ID: [-+*/<>=a-zA-Z_$][-+*/<>=?!a-zA-Z0-9_$]*;

// ================= Parser rules. ==================== //

// This is the root rule applied.
microScheme: expr*;

// Procedure declarations take the form (define (<var> <expr>*) <expr>)
procedureDeclaration: ('(' DEFINE '(' variable procedureParameters ')' procedureBody ')')
                    | ('(' DEFINE  '(' variable PERIOD procedureParameters ')' procedureBody ')' );
procedureParameters: expr*;
procedureBody: expr+;

// Declarations are definitions - either variables or procedures.
declExpr: procedureDeclaration;

// There are several different types of declarations.
expr: declExpr
    | lambdaExpr
    | condExpr
    | symbolExpr
    | applicationExpr
    | constant
    | variable;

// Lambda expressions take the form (lambda (<params>) <body>).
lambdaExpr: ('(' LAMBDA '(' lambdaParameters ')' lambdaBody ')')
          | ('(' LAMBDA '(' lambdaParameters PERIOD PERIOD PERIOD ')' lambdaBody ')');
lambdaParameters: expr*;
lambdaBody: expr+;

// Cond expressions take the form (cond (<condForm>))
condExpr: '(' COND ('(' condForm ')')+ ')'
        | '(' COND ('[' condForm ']')+ ')'
        | '(' COND ('(' condForm ')')+ '(' ELSE expr ')'')'
        | '(' COND ('[' condForm ']')+ '[' ELSE expr ']'')';
condForm: expr expr;

// Applications take the form (<expr> <expr>*)
applicationExpr: ( '(' expr applicationArgs ')' );
applicationArgs: expr*;

// Symbols take the form (quote | '(<expr>*) or <expr>)
symbolExpr: (QUOTE | SINGLE_QUOTE | BACK_TICK) symbolDatumRep;
symbolDatum: constant | variable | LAMBDA;
symbolDatumRep: (symbolDatum
                | ('(' symbolDatumRep PERIOD symbolDatumRep ')')
                | ('(' symbolDatumRep* ')'));

// Variables are, realistically, any symbol.
constant: STRINGLIT | CHARLIT | BOOLLIT | NUMBERLIT;
variable: ID;
```

**Crashing Input:**
```
(define (add1 l)
	(cond   [(null? l) '()]
    	    [else (cons (+ 1 (car l)) (add1 (cdr l)))]
    )
)
((lambda (x) (add1 (list 1 2 3 4 x))) 20)
```

**Exception/Error:**
```
java.lang.Throwable: Wrong startOffset: 18, textLength=0
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.openapi.editor.impl.CaretImpl.lambda$doSetSelection$6(CaretImpl.java:1078)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:421)
	at com.intellij.openapi.editor.impl.CaretImpl.doSetSelection(CaretImpl.java:1068)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1031)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1026)
	at com.intellij.openapi.editor.SelectionModel.setSelection(SelectionModel.java:155)
	at org.antlr.intellij.plugin.preview.PreviewPanel.onParserRuleSelected(PreviewPanel.java:508)
	at org.antlr.intellij.plugin.preview.HierarchyViewer.valueChanged(HierarchyViewer.java:159)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:2967)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:627)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.clearSelection(DefaultTreeSelectionModel.java:580)
	at java.desktop/javax.swing.JTree.clearSelection(JTree.java:2701)
	at java.desktop/javax.swing.JTree.setModel(JTree.java:861)
	at org.antlr.intellij.plugin.preview.HierarchyViewer.setTree(HierarchyViewer.java:63)
	at org.antlr.intellij.plugin.preview.PreviewPanel.lambda$clearTabs$1(PreviewPanel.java:363)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by parrt** [comment]
Hmm.. I can't seem to reproduce this with  2021.3.2 ultimate edition with the 1.17 plug-in.  this is on Apple silicon OS X 12.0.1.  I tried the latest plug-in version heading towards 1.18 with  community edition 2021.2 and that also works no matter how much I cut-and-paste, but I did fix some stuff related to indexing. But 2021.3.2 should definitely still fail though.  can you tell me which version of intellij? thanks!

**Comment by parrt** [comment]
I take it back. On a different grammar I just got it to give me that exception, but with 1.17.  I believe I understand why this is happening and I have already fixed it for 1.18. can I send you a plugin jar to try?

**Comment by parrt** [comment]
fixed by https://github.com/antlr/intellij-plugin-v4/issues/507

**Comment by JoshuaCrotts** [comment]
@parrt Sure. I think the reason I used 1.17 is because that’s the version in the IntelliJ plug-in marketplace.

**Comment by parrt** [comment]
please give a try :)

[antlr-intellij-plugin-v4-1.17.zip](https://github.com/antlr/intellij-plugin-v4/files/8149382/antlr-intellij-plugin-v4-1.17.zip)

**Comment by JoshuaCrotts** [comment]
@parrt Before I try it, is that the correct version? 1.17 is the version with the bug, right?

**Comment by parrt** [comment]
oh crap.  I have to bump the version number. standby

**Comment by parrt** [comment]
here you go...

[antlr-intellij-plugin-v4-1.18.zip](https://github.com/antlr/intellij-plugin-v4/files/8149405/antlr-intellij-plugin-v4-1.18.zip)

**Comment by JoshuaCrotts** [comment]
@parrt Looks like that fixed it. I'll post another update if I run into the issue again. Thanks!

**Comment by parrt** [comment]
woot!!!
