### ISSUE TITLE
Changing files while in ANTLR Preview caused exception

### ISSUE THREAD

**Issue by rennr** [antlr/intellij-plugin-v4#511]
**What I was doing:**

I was editing some text in the ANTLR Preview tool window. I had my cursor where there was an error in the interpretation and I realized I needed to change my grammar file. I believe some text was highlighted.

I opened another file -- not an ANTLR file but a C# file -- and I got the IDE exception below. I presume it has something to do with the highlighted text combined with switching away from an ANTLR file to another language file.

**Environment:**

Linux (Ubuntu 20.04)
Rider 2021.3.3
Plugin v. 1.17

Happy to provide additional information if needed.

```
java.lang.Throwable: Wrong startOffset: 408, textLength=0
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.openapi.editor.impl.CaretImpl.lambda$doSetSelection$6(CaretImpl.java:1078)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:421)
	at com.intellij.openapi.editor.impl.CaretImpl.doSetSelection(CaretImpl.java:1068)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1031)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1026)
	at com.intellij.openapi.editor.SelectionModel.setSelection(SelectionModel.java:155)
	at org.antlr.intellij.plugin.preview.PreviewPanel.onParserRuleSelected(PreviewPanel.java:508)
	at org.antlr.intellij.plugin.preview.HierarchyViewer.valueChanged(HierarchyViewer.java:159)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:2967)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:619)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.clearSelection(DefaultTreeSelectionModel.java:580)
	at java.desktop/javax.swing.JTree.clearSelection(JTree.java:2701)
	at java.desktop/javax.swing.JTree.setModel(JTree.java:861)
	at org.antlr.intellij.plugin.preview.HierarchyViewer.setTree(HierarchyViewer.java:63)
	at org.antlr.intellij.plugin.preview.PreviewPanel.lambda$clearTabs$1(PreviewPanel.java:363)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by parrt** [comment]
I *believe* I fixed this in https://github.com/antlr/intellij-plugin-v4/pull/506
