### ISSUE TITLE
got 'java.lang.ExceptionInInitializerError' when i enabled the antlr plugin and restart IDEA

### ISSUE THREAD

**Issue by NOknow95** [antlr/intellij-plugin-v4#654]
# IDEA and OS info
IntelliJ IDEA 2023.2 Beta (Ultimate Edition)
Build #IU-232.8660.48, built on July 12, 2023
Licensed to signup scooter
You have a perpetual fallback license for this version.
Subscription is active until August 1, 2025.
Runtime version: 17.0.7+7-b1000.6 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.8
GC: G1 Young Generation, G1 Old Generation
Memory: 1450M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    org.antlr.intellij.plugin (1.20)
    AceJump (3.8.14)
    HighlightBracketPair (1.4.1)
    org.jetbrains.plugins.hocon (2023.1.0)
    zielu.gittoolbox (500.0.13+213)

Kotlin: 232-1.8.21-release-380-IJ8660.48

# Stack trace created by intelij
```
java.lang.ExceptionInInitializerError
	at org.antlr.intellij.plugin.editor.ANTLRv4BraceMatcher.getPairs(ANTLRv4BraceMatcher.java:19)
	at cn.aprilviolet.highlightbracketpair.highlighter.DefaultAbstractBracketHighlighter.refresh(DefaultAbstractBracketHighlighter.java:84)
	at cn.aprilviolet.highlightbracketpair.highlighter.DefaultAbstractBracketHighlighter.<clinit>(DefaultAbstractBracketHighlighter.java:38)
	at cn.aprilviolet.highlightbracketpair.highlighter.BracketHighlighterFactory.getBraceHighlighterInstance(BracketHighlighterFactory.java:42)
	at cn.aprilviolet.highlightbracketpair.component.HighlightEditorCartListener.highlightEditorCurrentPair(HighlightEditorCartListener.java:64)
	at cn.aprilviolet.highlightbracketpair.component.HighlightEditorCartListener.caretPositionChanged(HighlightEditorCartListener.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:118)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:83)
	at jdk.proxy1/jdk.proxy1.$Proxy120.caretPositionChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.CaretModelImpl.fireCaretPositionChanged(CaretModelImpl.java:543)
	at com.intellij.openapi.editor.impl.CaretImpl.doMoveToLogicalPosition(CaretImpl.java:466)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToLogicalPosition(CaretImpl.java:613)
	at com.intellij.openapi.editor.impl.CaretImpl.lambda$moveToLogicalPosition$2(CaretImpl.java:323)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:414)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToLogicalPosition(CaretImpl.java:323)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$setCaretsAndSelections$4(CaretModelImpl.java:460)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:419)
	at com.intellij.openapi.editor.impl.CaretModelImpl.setCaretsAndSelections(CaretModelImpl.java:447)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorProvider.setStateImpl(TextEditorProvider.kt:188)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.setStateImpl(PsiAwareTextEditorProvider.kt:121)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.setEditorState(AsyncEditorLoader.kt:187)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.setState(TextEditorImpl.kt:135)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.restoreEditorState(FileEditorManagerImpl.kt:1212)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openInEdtImpl(FileEditorManagerImpl.kt:2133)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$openInEdtImpl(FileEditorManagerImpl.kt:121)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$openFileInEdt$2$1.invokeSuspend(FileEditorManagerImpl.kt:2085)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:43)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because "tokenIElementTypes" is null
	at org.antlr.intellij.adaptor.lexer.PSIElementTypeFactory.createTokenSet(PSIElementTypeFactory.java:131)
	at org.antlr.intellij.plugin.ANTLRv4TokenTypes.<clinit>(ANTLRv4TokenTypes.java:23)
	... 70 more

```

**Comment by NOknow95** [comment]
<img width="1208" alt="image" src="https://github.com/antlr/intellij-plugin-v4/assets/20488944/f32abca1-ec86-4291-8f21-2deb7432b57b">

**Comment by bjansen** [comment]
Wow, this happens before the plugin is done initializing :(
