### ISSUE TITLE
version 1.22 dies under the newest version of Intellij eap

### ISSUE THREAD

**Issue by greenhull** [antlr/intellij-plugin-v4#671]
version info:

IntelliJ IDEA 2023.3 EAP (Ultimate Edition)
Build #IU-233.11555.11, built on November 1, 2023
Licensed to IntelliJ IDEA EAP user: Chester John
Expiration date: December 1, 2023
Runtime version: 17.0.9+7-b1087.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  editor.focus.mode.color.light=e0861f
  ide.editor.tab.selection.animation=true
  debugger.new.tool.window.layout=true
  ide.animate.toolwindows=true
  ide.new.editor.tabs.vertical.borders=true
  ide.experimental.ui=true
  ide.balloon.shadow.size=0
  editor.focus.mode.color.dark=e0861f
Non-Bundled Plugins:
  com.intellij.javafx (1.0.4)
  Gradle View (4.0.0)
  com.jetbrains.space (233.11555.17)
  com.godwin.json.parser (1.7.1)
  com.intellij.properties.bundle.editor (233.11555.11)
  org.sylfra.idea.plugins.linessorter (1.0.1)
  com.dubreuia.tool (2.6.2)
  com.zt.json-editor (2.9.1)
  String Manipulation (9.11.3)
  tarn.gradle.dependencies (1.6.2)
  GrepConsole (12.22.1-IJ2021.1)
  PlantUML integration (7.3.0-IJ2023.2)
  com.github.platan.gradle-dependencies-formatter (0.6.1)
  com.yiycf.plugins.mavenDependencyHelper (2.5)
  com.gluonhq.plugin.intellij (2.8.6)
  MavenRunHelper (4.26.0-IJ2022.2)
  com.intellij.ml.llm (233.11555.11)
  izhangzhihao.rainbow.brackets (2023.3.7)
  com.chrisrm.idea.MaterialThemeUI (8.13.2)
  org.mallowigi.idea.MaterialThemeUI.HighContrast (2024.1.1)
  GradleDependenciesHelper (1.16)
  org.sonarlint.idea (10.0.0.76954)
  com.mallowigi (94.1.0)
  com.kn.diagrams.generator.generator (2022.2.0)
  org.jetbrains.plugins.docker.gateway (233.11555.17)
Kotlin: 233-1.9.0-release-358-IJ11555.11

**Comment by greenhull** [comment]
stack dump of problem

java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because "this.tokenElementTypes" is null
	at org.antlr.intellij.adaptor.lexer.ANTLRLexerAdaptor.getTokenType(ANTLRLexerAdaptor.java:188)
	at org.antlr.intellij.adaptor.lexer.ANTLRLexerAdaptor.getTokenType(ANTLRLexerAdaptor.java:178)
	at com.intellij.openapi.editor.ex.util.ValidatingLexerWrapper.getTokenType(ValidatingLexerWrapper.java:50)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.doSetText(LexerEditorHighlighter.java:433)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.setText(LexerEditorHighlighter.java:410)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$createEditorBuilder$2$highlighterDeferred$1$1.invoke(PsiAwareTextEditorProvider.kt:67)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$createEditorBuilder$2$highlighterDeferred$1$1.invoke(PsiAwareTextEditorProvider.kt:63)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:108)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadBlocking$2.invoke$lambda$0(InternalReadAction.kt:86)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1089)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadBlocking$2.invoke(InternalReadAction.kt:85)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadBlocking$2.invoke(InternalReadAction.kt:83)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
	at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:198)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:197)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadBlocking(InternalReadAction.kt:83)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:75)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:65)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:44)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:40)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadActionBlocking(coroutines.kt:124)
	at com.intellij.openapi.application.CoroutinesKt.readActionBlocking(coroutines.kt:93)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$createEditorBuilder$2$highlighterDeferred$1.invokeSuspend(PsiAwareTextEditorProvider.kt:63)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by oovm** [comment]
Same problem here.

Every time I installed it, it was fine, but when I started it again, it was broken again.

**Comment by greenhull** [comment]
it seems ok with current release
