### ISSUE TITLE
plugin causes error in Intellij 2024.2

### ISSUE THREAD

**Issue by SingingBush** [antlr/intellij-plugin-v4#711]
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.antlr.intellij.plugin.actions.GenerateParserAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.antlr.intellij.plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

![image](https://github.com/user-attachments/assets/e4552e44-a923-433c-bb19-1ab05f29ec43)

**Comment by bwinters** [comment]
This is the same as https://github.com/antlr/intellij-plugin-v4/issues/696.
